postgres_version: 16
replication_user: replicator
replication_password: Test1234
postgres_data_dir: /var/lib/postgresql/{{ postgres_version }}/main
postgres_conf_dir: /etc/postgresql/{{ postgres_version }}/main
listen_addresses: '*'
max_wal_senders: 10
wal_level: replica
archive_mode: on
